# Generated by Django 5.0.3 on 2024-04-05 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('isBuyer', models.BooleanField(default=False)),
                ('isSeller', models.BooleanField(default=False)),
                ('organization', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('lastSession', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('idOrder', models.IntegerField(primary_key=True, serialize=False)),
                ('quality', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('destiny', models.CharField(max_length=255)),
                ('type', models.SmallIntegerField()),
                ('idBuyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='recolection',
            fields=[
                ('idRecolection', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
