# Generated by Django 5.0.3 on 2024-04-02 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOrder', models.IntegerField()),
                ('quality', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('destiny', models.CharField(max_length=255)),
                ('type', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('isBuyer', models.BooleanField(default=False)),
                ('isSeller', models.BooleanField(default=False)),
                ('organization', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('lastSession', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='recolection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRecolection', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='idBuyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
