# Generated by Django 5.0.3 on 2024-04-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_user_recolection_order_idbuyer'),
    ]

    operations = [
    ]
