# Generated by Django 5.0.3 on 2024-04-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240401_2342'),
    ]

    operations = [
    ]
